### PR TITLE
Remove dependsOn configuration, use CopySpec to evaluate `files`

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
@markelliot, this is a breaking change, but one I believe we should make.

**Comment by markelliot** [comment]
yeah, it's fine. I guess being idiomatic is going to beat convenience (ie most of the time you want not just to consume the distTar outputs but also to depend on the actual task.

**Comment by uschi2000** [comment]
you can still do exactly that, but with a few more characters. it's more gradle standard style, i guess.
```
distribution {
  files tasks.distTar.outputs
}
```

instead of
```
distribution {
  dependsOn distTar
}
```

**Comment by markelliot** [comment]
Does saying you depend on tasks.distTar.outputs actually mean you depend on distTar? (at least in Gradle 2.x this was not the case)

**Comment by uschi2000** [comment]
yes it does. there's a test for this (see latest commit).

**Comment by markelliot** [comment]
wfm 👍

**Pull request merged**
