### PR TITLE
dockerRemoveContainer must run after dockerStop

### PR DESCRIPTION
**Pull request by khalid17160**
[d.txt](https://github.com/palantir/gradle-docker/files/2524791/d.txt)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-docker](https://github.com/palantir/gradle-docker), @khalid17160! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by pkoenig10** [comment]
@khalid17160 this looks good, can you just add a test that ensure these tasks are run in the correct order?

**Comment by khalid17160** [comment]
I think this might not be a good place for this code.

**Comment by khalid17160** [comment]
What text you mean, are you talking about comments?

**Pull request closed without merging**
