### PR TITLE
Gradle 4.4 support

### PR DESCRIPTION
**Pull request by kyegupov**
Internal APIs have changed for UsageContext and Usage, so quite a bunch of changes were needed to adapt to that.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-docker](https://github.com/palantir/gradle-docker), @kyegupov! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by uschi2000** [comment]
I'm fine with this. The alternative would to remove the support for docker dependencies, not sure anyone uses this? @jared2501 @gracew

**Comment by jared2501** [comment]
No where ended up taking the docker dependencies stuff as far as I know

**Comment by gracew** [comment]
I think we use docker dependencies incorrectly in a bunch of places. I'm fine with either merging this or deleting `DockerComponent`.

**Comment by billbindi** [comment]
I can tell you that we do in fact use this and I would appreciate this remaining, but just upgrading (i.e. merging this pr) for the newer gradle APIs.

**Comment by uschi2000** [comment]
OK, too bad.

**Comment by uschi2000** [comment]
thanks @kyegupov

**Comment by billbindi** [comment]
@uschi2000 it looks like this has had some troubles publishing. Judging by the gradle plugin page (https://plugins.gradle.org/plugin/com.palantir.docker) it hasn't published since `0.13.0`. This most recent one looks like a test failure, which is odd since the pr passed that test just fine. Any chance you could try a retrigger to see if it is just a flickering test?

**Comment by uschi2000** [comment]
Working on it.

**Comment by uschi2000** [comment]
0.17.0 is now on bintray. docker plugin portal publishing is still broken.

**Pull request merged**
