### PR TITLE
Change default template to docker-compose.template.yml

### LINKED ISSUE #71: Change template name to docker-compose.template.yml
Could we rename the `docker-compose.yml.template` template default filename to `docker-compose.template.yml`?

IDEs won't do yaml syntax highlighting on a yaml file with a ".template" extension.

I know I can use the following block:

``` groovy
dockerCompose {
    template 'docker-compose.template.yml'
}
```

But, I would prefer a better default to avoid adding these lines to my build.gradle

### PR DESCRIPTION
**Pull request by pkoenig10**
Fixes #71

### CODE REVIEW

**Comment by iamdanfox** [comment]
@pkoenig10 btw as you've been maintaining this repo without really needing the infra team's involvement, would you like us to get rid of that CODEOWNERs thing?

**Comment by pkoenig10** [comment]
I'm good either way. It's helpful just to get another set of eyes on any changes I make.

**Comment by iamdanfox** [comment]
Cool, for this specific PR, I think this would break a bunch of internal repo's usage.  Could we coordinate this with an excavator PR or even better, make this fallback to reading from the old file (just printing a warning)?

**Comment by pkoenig10** [comment]
Yes but it will be a very obvious break and a simple fix.

Let's coordinate with an excavator PR. Falling back to another file would introduce a lot of complexity here.

**Comment by iamdanfox** [comment]
@pkoenig10 did you look into the excavator approach here?

**Comment by pkoenig10** [comment]
I haven't had the time, but this change is not high priority. I'll follow up here once I've looked into it.

**Pull request closed without merging**
