### PR TITLE
Add ability to set network parameter.

### PR DESCRIPTION
**Pull request by ivanobulo**
## Before this PR
Network configuration for building a docker image was unavailable

## After this PR
Added ability to specify network configuration when building a docker image

## Possible downsides?
None

### CODE REVIEW

**Comment by ivanobulo** [comment]
bump

**Comment by ivanobulo** [comment]
@ferozco would you please review it?

**Comment by ferozco** [comment]
👍

**Comment by ferozco** [comment]
sorry for the delay thanks @ivanobulo

**Comment by msmsimondean** [comment]
Hi @ferozco.  Sorry to bother you.  Are there any plans to do a release for this change?  I've just encountered an issue where the fix is to set the network for Docker build.  Thanks!

**Comment by ferozco** [comment]
@msmsimondean you bet! I've cut 0.26.0 with the fix

**Comment by ivanobulo** [comment]
@msmsimondean here the temporary workaround:
```kotlin
val dockerTask = tasks.getByName("docker", Exec::class)
dockerTask.doFirst {
    logger.info("Fixing docker build to use 'host' network")
    val cmd  = dockerTask.commandLine
    val buildIdx = cmd.indexOf("build")
    if (buildIdx >= 0) {
        cmd.addAll(buildIdx + 1, listOf("--network", "host"))
        dockerTask.setCommandLine(cmd)
    }
    logger.lifecycle("Executing command \"${dockerTask.commandLine.joinToString(" ")}\"")
}
```

**Comment by msmsimondean** [comment]
That's awesome.  Thanks @ferozco!

**Pull request merged**
