### PR TITLE
Remove StyledTextOutputFactory

### LINKED ISSUE #119: Gradle 3 Support For Docker-Run
When trying to use docker-run under gradle 3 I get the error

>  `No service of type StyledTextOutputFactory available in ProjectScopeServices.`

Google suggests this is a compatibility issue with gradle 3.

### PR DESCRIPTION
**Pull request by derenrich**
Resolves #119

### CODE REVIEW

**Comment by uschi2000** [comment]
Oh, this might actually be a problem even with 3.4.

**Comment by uschi2000** [comment]
Sorry, I thought you were referring to a different issue.

**Comment by derenrich** [comment]
oh

**Comment by derenrich** [comment]
Also, dude 3.4 released 9 days ago

**Comment by uschi2000** [comment]
What's the problem you're seeing?

**Comment by uschi2000** [comment]
Yes, it did.

**Comment by derenrich** [comment]
I'm getting different errors after upgrading to 3.4

Edit: working on hunting it down now

**Comment by derenrich** [comment]
Oh no that was user error. Upgrading seemed to fix it.

**Comment by uschi2000** [comment]
Cool, cheers.

**Pull request closed without merging**
