### PR TITLE
Docker compose down

### PR DESCRIPTION
**Pull request by tkgregory**
## Before this PR
There was no ability to call docker compose down from the Gradle plugin

## After this PR
==COMMIT_MSG==
New dockerComposeDown Gradle task available in Docker Compose plugin.
==COMMIT_MSG==

## Possible downsides?
None

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-docker](https://github.com/palantir/gradle-docker), @tkgregory! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by tkgregory** [comment]
@ferozco are you able to take a look at this? Please advise how to proceed.

**Comment by tkgregory** [comment]
Bump

**Review by ferozco — APPROVED** [review]

**Comment by ferozco** [comment]
Thanks Tom! sorry for the delay in reviewing

**Comment by ferozco** [comment]
Looks like the bots can't generate a changelog because the head of the PR is on your fork. Can you manually add a changelog?

**Comment by tkgregory** [comment]
Hi @ferozco I added a changelog but the check is still failing. Do you know exactly what is expected please?

**Comment by ferozco** [comment]
🤦‍♂ looks like this repo hasn't been migrated to use structured changelogs yet. I'll follow up and clean this up

**Pull request merged**
