### PR TITLE
Add ignoreExitValue option to Docker Run Plugin

### PR DESCRIPTION
**Pull request by giancarlobastos**
## Before this PR
If the command executed by the Docker Run Plugin exits with a code different from zero, it will break the Gradle execution.

## After this PR
It will add the option to ignore the exit code returned from the command.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-docker](https://github.com/palantir/gradle-docker), @giancarlobastos! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giancarlobastos** [comment]
@palantirtech could you review it?

**Comment by giancarlobastos** [comment]
@saw303 @GrahamDennis @invliD

**Comment by giancarlobastos** [comment]
@michael-yx-wu, could you review it?

**Comment by fawind** [comment]
Thanks for contributing and sorry for the delayed review. The change looks good!

The build CI task is currently failing because the gradle publishing-plugin does not support forks. Can you merge in `develop` (we need this commit: https://github.com/palantir/gradle-docker/commit/0aea272a61c511f4549081613b6d84869390a485) to get the PR unblocked?

**Review by fawind — APPROVED** [review]

**Pull request merged**
