### PR TITLE
Clarify doc on copySpec

### PR DESCRIPTION
**Pull request by AnEmortalKid**
update copy spec example with something that works

## Before this PR
Could not figure out how to use `copySpec`

## After this PR
A clear working example of copy spec is in the doc

Relevant to #168

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-docker](https://github.com/palantir/gradle-docker), @AnEmortalKid! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by pkoenig10** [comment]
@AnEmortalKid can you elaborate on or provide an example for why the existing copy spec example didn't work for you? It seems to work as expected for me.

**Comment by AnEmortalKid** [comment]
Ah, it might be not doing what I thought it would.

So, my desired state:

```
build/
  docker/
    'myfile.txt'
    data/
      'super-secret-password.txt'
```

Using:
```
  files 'myfile.txt'
  copySpec.from("secretData/").into("data")
```

I actually get:
```
build/
  docker/
    data/
      'myfile.txt'
      'super-secret-password.txt'
```

Maybe I misread the: 

> The specified files are collected in a Gradle CopySpec which may be copied into the Docker build context directory. The underlying CopySpec may also be used to copy entire directories into the build context. The following example adds the aforementioned archive and text file to the CopySpec, uses the CopySpec to add all files from src/myDir into the CopySpec, then finally executes the copy into the docker build context directory myDir

Particularly:

> The following example adds the aforementioned archive and text file to the CopySpec, uses the CopySpec to add all files from src/myDir into the CopySpec, then finally executes the copy into the docker build context directory myDir

Maybe if we clarify with the example output with regards to the `build/docker` that would help others? It didn't seem super obvious to me everything would end under `myDir`.

**Comment by pkoenig10** [comment]
Yeah I think we can clarify the last sentence a bit.

> ... then finally executes the copy into the directory myDir in docker build context.

**Comment by AnEmortalKid** [comment]
@pkoenig10 lmk if the output example is 2 much, and i can remove it. Hopefully the doc is more clear!

**Review by pkoenig10 — APPROVED** [review]
LGTM, thanks @AnEmortalKid!

**Comment by PerMildner** [comment]
The "The final structure will be" in the updated documentation seems to document the current behavior but it does not answer the original question, i.e. how to get the non-flat result:

```
build/
  docker/
    'myfile.txt'
    data/
      'super-secret-password.txt'
```
It is unexpected, and not useful, that the `files` argument ends up in the `into`-folder used in a subsequent `copySpec...into(...)` call. Also, using `copySpec` with more than one `from` where the `from` has a closure with `exclude` seems to apply the `exclude` to the entire copy.

So, perhaps there is really some underlying bug in how copy specs are combined in the final copy. 

In either case the documentation would be more useful if it contained an example corresponding to the more complex structure above. It looks like https://github.com/palantir/gradle-docker/issues/168#issuecomment-375947722 may be relevant.

**Pull request merged**
